-- 膨胀到 5000 产品（PRD1001~PRD5000）
DELETE FROM product_process WHERE product_id >= 'PRD2001';
DELETE FROM graph_product WHERE id >= 'PRD2001';

-- 三角 cross join 生成 2001~5000 范围的产品 id
INSERT INTO graph_product(id, name, category)
SELECT CONCAT('PRD', LPAD(num, 4, '0')), CONCAT('benchmark-', num), 'benchmark'
FROM (
  SELECT (a.n + b.n*10 + c.n*100 + d.n*1000 + e.n*10000) AS num
  FROM (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
        UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a
  CROSS JOIN (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
        UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b
  CROSS JOIN (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
        UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c
  CROSS JOIN (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
        UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d
  CROSS JOIN (SELECT 0 n UNION SELECT 1) e
) seq
WHERE num BETWEEN 2001 AND 5000;

-- 复制 PRD002 的 14 道工序给每个新产品
INSERT INTO product_process(product_id, process_id)
SELECT gp.id, pp.process_id
FROM graph_product gp
CROSS JOIN product_process pp
WHERE pp.product_id = 'PRD002' AND gp.id >= 'PRD2001';

SELECT 'graph_product' AS t, COUNT(*) AS c FROM graph_product
UNION ALL SELECT 'product_process', COUNT(*) FROM product_process;
